FROM node:18-alpine AS base

RUN apk add --no-cache libc6-compat

WORKDIR /app

FROM base AS deps

COPY package.json package-lock.json* ./

RUN npm install @igrp/navbar-library@1.0.7 --registry=https://sonatype.nosi.cv/repository/npm-group/

RUN npm install

FROM base AS build

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

RUN npm run build

FROM node:18-alpine AS production

ENV NODE_ENV=production

WORKDIR /app
COPY --from=build /app/.next /app/.next
COPY --from=build /app/.next/static /app/.next/static
COPY --from=build /app/public /app/public
COPY --from=deps /app/package*.json ./
COPY --from=deps /app/node_modules ./node_modules

EXPOSE 80

RUN addgroup -S nextjs && adduser -S nextjs -G nextjs
USER nextjs

CMD ["npm", "start"]