#!/bin/bash
set -e

# iGRP Access Management database
echo "Creating database for access management platforms: $IGRP_ACCESS_MANAGEMENT_DB_NAME"
psql -v ON_ERROR_STOP=1 --username "$IGRP_DB_USER" --dbname "$IGRP_DB_NAME" <<-EOSQL
    CREATE DATABASE $IGRP_ACCESS_MANAGEMENT_DB_NAME;
    CREATE USER $IGRP_ACCESS_MANAGEMENT_DB_USER WITH ENCRYPTED PASSWORD '$IGRP_ACCESS_MANAGEMENT_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $IGRP_ACCESS_MANAGEMENT_DB_NAME TO $IGRP_ACCESS_MANAGEMENT_DB_USER;
EOSQL

# iGRP Identity Access Management database
echo "Creating database for IAM: $IGRP_IAM_DB_NAME"
psql -v ON_ERROR_STOP=1 --username "$IGRP_DB_USER" --dbname "$IGRP_DB_NAME" <<-EOSQL
    CREATE DATABASE $IGRP_IAM_DB_NAME;
    CREATE USER $IGRP_IAM_DB_USER WITH ENCRYPTED PASSWORD '$IGRP_IAM_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $IGRP_IAM_DB_NAME TO $IGRP_IAM_DB_USER;
EOSQL

# iGRP App Logic database
echo "Creating database for app logic: $IGRP_APP_LOGIC_DB_NAME"
psql -v ON_ERROR_STOP=1 --username "$IGRP_DB_USER" --dbname "$IGRP_DB_NAME" <<-EOSQL
    CREATE DATABASE $IGRP_APP_LOGIC_DB_NAME;
    CREATE USER $IGRP_APP_LOGIC_DB_USER WITH ENCRYPTED PASSWORD '$IGRP_APP_LOGIC_DB_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $IGRP_APP_LOGIC_DB_NAME TO $IGRP_APP_LOGIC_DB_USER;
EOSQL