stages:
  - test
  - build
variables:
  SONAR_SCANNER_OPTS: "-Xmx1024m"

test:
  stage: test
  image: node:slim
  script:
    - npm install
    - npm run test -- --coverage
  artifacts:
    paths:
      - coverage/
    expire_in: 1 day
  only:
    - master

sonarqube_scan:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.projectKey=my_node_project_key
  only:
    - master

build_packagedev:
  image: node:slim
  stage: build
  only:
    - master
  script:
    - npm install
    - npm run build
    - npm publish --registry=https://sonatype.nosi.cv/repository/igrp/
