import { register } from './index';
import alertModule, { ALERT } from './alert/index';
import alertDialogModule, { ALERT_DIALOG } from './alertDialog';
import aspectModule, { ASPECT } from './aspect';
import badgeModule, { BADGE } from './badge';
import buttonModule, { BUTTON } from './button';
import cardModule, { CARD } from './card';
import cardContentModule, { CARD_CONTENT } from './card/children/cardContent';
import cardFooterModule, { CARD_FOOTER } from './card/children/cardFooter';
import cardHeaderModule, { CARD_HEADER } from './card/children/cardHeader';
import carouselModule, { CAROUSEL } from './carousel';
import chartModule, { AREACHART } from './areachart';
import chatModule, { CHAT } from './chat';
import checkboxModule, { CHECKBOX } from './checkbox';
import columnModule, { COLUMN } from './column';
import columnsModule, { COLUMNS } from './columns';
import comboboxModule, { COMBOBOX } from './combobox';
import componentModule, { COMPONENT } from './component';
import containerModule, { CONTAINER } from './container';
import datePickerRangeModule, { DATE_PICKER_RANGE } from './datePickerRange/index';
import dropdownModule, { DROPDOWN } from './dropdown';
import dropdownItemModule, { DROPDOWN_ITEM } from './dropdown/children/dropdownItem';
import flexModule, { FLEX } from './flex';
import formListModule, { FORM_LIST } from './formList';
import formModule, { FORM } from './form';
import fragmentModule, { FRAGMENT } from './fragment';
import gridModule, { GRID } from './grid';
import headlineModule, { HEADLINE } from './headline';
import horizontalBarChartModule, { HORIZONTAL_BAR_CHART } from './horizontalbarchart';
import iconModule, { ICON } from './icon';
import infoCardModule, { INFO_CARD } from './infoCard';
import infoItemModule, { INFO_ITEM } from './infoCard/children/infoItem';
import infoSectionModule, { INFO_SECTION } from './infoCard/children/infoSection';
import inputAddOnModule, { INPUT_ADD_ON } from './inputAddOn';
import inputColorModule, { INPUT_COLOR } from './inputColor';
import inputDatePickerModule, { INPUT_DATE_PICKER } from './inputDatePicker';
import inputFileModule, { INPUT_FILE } from './inputFile';
import inputHiddenModule, { INPUT_HIDDEN } from './inputHidden/index';
import inputNumberModule, { INPUT_NUMBER } from './inputNumber';
import inputPasswordModule, { INPUT_PASSWORD } from './inputPassword';
import inputPhoneModule, { INPUT_PHONE } from './inputPhone';
import inputSearchModule, { INPUT_SEARCH } from './inputSearch';
import inputTextModule, { INPUT_TEXT } from './inputText';
import inputTextareaModule, { INPUT_TEXTAREA } from './inputTextarea';
import inputTimeModule, { INPUT_TIME } from './inputTime';
import inputUrlModule, { INPUT_URL } from './inputUrl';
import labelModule, { LABEL } from './label';
import lineChartModule, { LINECHART } from './linechart';
import menuNavigationModule, { MENU_NAVIGATION } from './menuNavigation/index';
import menuNavigationItemModule, { MENU_NAVIGATION_ITEM } from './menuNavigation/children/menuNavigationItem/index';
import modalDialogModule, { MODAL_DIALOG } from './modalDialog/index';
import pageModule, { PAGE } from './page';
import pageHeaderModule, { PAGEHEADER } from './pageHeader';
import paragraphModule, { PARAGRAPH } from './paragraph';
import pdfViewerModule, { PDF_VIEWER } from './pdfViewer/index';
import pieChartModule, { PIECHART } from './piechart';
import radarChartModule, { RADARCHART } from './radarchart';
import radialBarChartModule, { RADIAL_BAR_CHART } from './radialbarchart';
import radioModule, { RADIO } from './radio';
import repetitiveListModule, { REPETITIVE_LIST } from './repetitiveList';
import sectionModule, { SECTION } from './section';
import selectModule, { SELECT } from './select';
import separatorModule, { SEPARATOR } from './separator/index';
import sliderModule, { SLIDER } from './slider';
import stackModule, { STACK } from './stack';
import statsCardModule, { STATS_CARD } from './statsCard';
import switchModule, { SWITCH } from './switch';
import tableModule, { TABLE } from './table';
import tableBadgeModule, { TABLE_TEXT_CELL } from './table/children/tableTextCell';
import tableCheckboxCellModule, { TABLE_CHECKBOX_CELL } from './table/children/tableCheckboxCell/index';
import tableColumnsModule, { TABLE_COLUMNS } from './table/children/tableColumns';
import tableExpanderCellModule, { TABLE_EXPANDER_CELL } from './table/children/tableExpanderCell';
import tableAmountCellModule, { TABLE_AMOUNT_CELL } from './table/children/tableAmountCell';
import tableDateCellModule, { TABLE_DATE_CELL } from './table/children/tableDateCell';
import tableBadgeCellModule, { TABLE_BADGE_CELL } from './table/children/tableBadgeCell';
import tableDateFilterModule, { TABLE_DATE_FILTER } from './table/children/tableDateFilter';
import tableDropdownFilterModule, { TABLE_DROPDOWN_FILTER } from './table/children/tableDropdownFilter';
import tableMinMaxFilterModule, { TABLE_MINMAX_FILTER } from './table/children/tableMixMaxFilter';
import tableInputFilterModule, { TABLE_INPUT_FILTER } from './table/children/tableInputFilter';
import tableSelectFilterModule, { TABLE_SELECT_FILTER } from './table/children/tableSelectFilter';
import tableFacetedFilterModule, { TABLE_FACETED_FILTER } from './table/children/tableFacetedFilter';
import tableButtonListCellModule, { TABLE_BUTTON_LIST_CELL } from './table/children/tableButtonListCell';
import tableActionListCellModule, { TABLE_ACTION_LIST_CELL } from './table/children/tableActionListCell';
import tableHiddenCellModule, { TABLE_HIDDEN_CELL } from './table/children/tableHiddenCell/index';
import tableAlertButtonModule, { TABLE_ALERT_BUTTON } from './table/children/tableAlertButton';
import tableLinkButtonModule, { TABLE_LINK_BUTTON } from './table/children/tableLinkButton';
import tableModalButtonModule, { TABLE_MODAL_BUTTON } from './table/children/tableModalButton';
import tableDropdownMenuCellModule, { TABLE_DROPDOWN_MENU_CELL } from './table/children/tableDropdownMenuCell';
import tableAlertDropdownItemModule, { TABLE_ALERT_DROPDOWN_ITEM } from './table/children/tableAlertDropdownItem';
import tableLinkDropdownItemModule, { TABLE_LINK_DROPDOWN_ITEM } from './table/children/tableLinkDropdownItem';
import tableModalDropdownItemModule, { TABLE_MODAL_DROPDOWN_ITEM } from './table/children/tableModalDropdownItem';
import tableCustomDropdownItemModule, { TABLE_CUSTOM_DROPDOWN_ITEM } from './table/children/tableCustomDropdownItem/index';
import tableAlertActionModule, { TABLE_ALERT_ACTION } from './table/children/tableAlertAction';
import tableLinkActionModule, { TABLE_LINK_ACTION } from './table/children/tableLinkAction';
import tableModalActionModule, { TABLE_MODAL_ACTION } from './table/children/tableModalAction';
import tableFiltersModule, { TABLE_FILTERS } from './table/children/tableFilters';
import tabsModule, { TABS } from './tabs';
import tabsItemModule, { TABS_ITEM } from './tabs/children/tabsItem/index';
import verticalBarChartModule, { VERTICAL_BAR_CHART } from './verticalbarchart';
import textModule, { TEXT } from './text/index';
import textListModule, { TEXT_LIST } from './textList/index';
import textListItemModule, { TEXT_LIST_ITEM } from './textList/children/textListItem/index';
import textListItemContentModule, { TEXT_LIST_ITEM_CONTENT } from './textList/children/textListItemContent/index';
import textListSubItemModule, { TEXT_LIST_SUBITEMS } from './textList/children/textListSubItems/index';

export function registerAllComponents() {
  register(ALERT, alertModule.register);
  register(ALERT_DIALOG, alertDialogModule.register);
  register(AREACHART, chartModule.register);
  register(ASPECT, aspectModule.register);
  register(BADGE, badgeModule.register);
  register(BUTTON, buttonModule.register);
  register(CARD, cardModule.register);
  register(CARD_CONTENT, cardContentModule.register);
  register(CARD_FOOTER, cardFooterModule.register);
  register(CARD_HEADER, cardHeaderModule.register);
  register(CAROUSEL, carouselModule.register);
  register(CHAT, chatModule.register);
  register(CHECKBOX, checkboxModule.register);
  register(COLUMN, columnModule.register);
  register(COLUMNS, columnsModule.register);
  register(COMBOBOX, comboboxModule.register);
  register(COMPONENT, componentModule.register);
  register(CONTAINER, containerModule.register);
  register(DATE_PICKER_RANGE, datePickerRangeModule.register);
  register(DROPDOWN, dropdownModule.register);
  register(DROPDOWN_ITEM, dropdownItemModule.register);
  register(FLEX, flexModule.register);
  register(FORM, formModule.register);
  register(FORM_LIST, formListModule.register);
  register(FRAGMENT, fragmentModule.register);
  register(GRID, gridModule.register);
  register(HEADLINE, headlineModule.register);
  register(HORIZONTAL_BAR_CHART, horizontalBarChartModule.register);
  register(ICON, iconModule.register);
  register(INFO_CARD, infoCardModule.register);
  register(INFO_ITEM, infoItemModule.register);
  register(INFO_SECTION, infoSectionModule.register);
  register(INPUT_ADD_ON, inputAddOnModule.register);
  register(INPUT_COLOR, inputColorModule.register);
  register(INPUT_DATE_PICKER, inputDatePickerModule.register);
  register(INPUT_FILE, inputFileModule.register);
  register(INPUT_HIDDEN, inputHiddenModule.register);
  register(INPUT_NUMBER, inputNumberModule.register);
  register(INPUT_PASSWORD, inputPasswordModule.register);
  register(INPUT_PHONE, inputPhoneModule.register);
  register(INPUT_SEARCH, inputSearchModule.register);
  register(INPUT_TEXT, inputTextModule.register);
  register(INPUT_TEXTAREA, inputTextareaModule.register);
  register(INPUT_TIME, inputTimeModule.register);
  register(INPUT_URL, inputUrlModule.register);
  register(LABEL, labelModule.register);
  register(LINECHART, lineChartModule.register);
  register(MENU_NAVIGATION, menuNavigationModule.register);
  register(MENU_NAVIGATION_ITEM, menuNavigationItemModule.register);
  register(MODAL_DIALOG, modalDialogModule.register);
  register(PAGE, pageModule.register);
  register(PAGEHEADER, pageHeaderModule.register);
  register(PARAGRAPH, paragraphModule.register);
  register(PDF_VIEWER, pdfViewerModule.register);
  register(PIECHART, pieChartModule.register);
  register(RADARCHART, radarChartModule.register);
  register(RADIAL_BAR_CHART, radialBarChartModule.register);
  register(RADIO, radioModule.register);
  register(REPETITIVE_LIST, repetitiveListModule.register);
  register(SECTION, sectionModule.register);
  register(SELECT, selectModule.register);
  register(SEPARATOR, separatorModule.register);
  //register(SLIDER, sliderModule.register);
  register(STACK, stackModule.register);
  register(STATS_CARD, statsCardModule.register);
  register(SWITCH, switchModule.register);
  register(TABLE, tableModule.register);
  register(VERTICAL_BAR_CHART, verticalBarChartModule.register);

  // Table Columns
  register(TABLE_TEXT_CELL, tableBadgeModule.register);
  register(TABLE_COLUMNS, tableColumnsModule.register);
  register(TABLE_CHECKBOX_CELL, tableCheckboxCellModule.register);
  register(TABLE_EXPANDER_CELL, tableExpanderCellModule.register);
  register(TABLE_FILTERS, tableFiltersModule.register);
  register(TABLE_AMOUNT_CELL, tableAmountCellModule.register);
  register(TABLE_DATE_CELL, tableDateCellModule.register);
  register(TABLE_BADGE_CELL, tableBadgeCellModule.register);
  register(TABLE_BUTTON_LIST_CELL, tableButtonListCellModule.register);
  register(TABLE_DROPDOWN_MENU_CELL, tableDropdownMenuCellModule.register);
  register(TABLE_ACTION_LIST_CELL, tableActionListCellModule.register);
  register(TABLE_HIDDEN_CELL, tableHiddenCellModule.register);

  // Action Buttons
  register(TABLE_ALERT_BUTTON, tableAlertButtonModule.register);
  register(TABLE_MODAL_BUTTON, tableModalButtonModule.register);
  register(TABLE_LINK_BUTTON, tableLinkButtonModule.register);

  // Dropdown Items
  register(TABLE_ALERT_DROPDOWN_ITEM, tableAlertDropdownItemModule.register);
  //register(TABLE_MODAL_DROPDOWN_ITEM, tableModalDropdownItemModule.register);
  register(TABLE_CUSTOM_DROPDOWN_ITEM, tableCustomDropdownItemModule.register);
  register(TABLE_LINK_DROPDOWN_ITEM, tableLinkDropdownItemModule.register);

  // Action Items
  register(TABLE_ALERT_ACTION, tableAlertActionModule.register);
  register(TABLE_MODAL_ACTION, tableModalActionModule.register);
  register(TABLE_LINK_ACTION, tableLinkActionModule.register);

  // Table Filters
  register(TABLE_DATE_FILTER, tableDateFilterModule.register);
  register(TABLE_DROPDOWN_FILTER, tableDropdownFilterModule.register);
  register(TABLE_INPUT_FILTER, tableInputFilterModule.register);
  register(TABLE_MINMAX_FILTER, tableMinMaxFilterModule.register);
  register(TABLE_SELECT_FILTER, tableSelectFilterModule.register);
  register(TABLE_FACETED_FILTER, tableFacetedFilterModule.register);
  register(TABS, tabsModule.register);
  register(TABS_ITEM, tabsItemModule.register);
  register(TEXT, textModule.register);
  register(TEXT_LIST, textListModule.register);
  register(TEXT_LIST_ITEM, textListItemModule.register);
  register(TEXT_LIST_ITEM_CONTENT, textListItemContentModule.register);
  register(TEXT_LIST_SUBITEMS, textListSubItemModule.register);

}