import { register } from './index';
import aspectModule, { ASPECT } from './aspect';
import buttonModule, { BUTTON } from './button';
import cardModule, { CARD } from './card';
import carouselModule, { CAROUSEL } from './carousel';
import chartModule, { CHART } from './chart';
import checkboxModule, { CHECKBOX } from './checkbox';
import columnModule, { COLUMN } from './column';
import columnsModule, { COLUMNS } from './columns';
import containerModule, { CONTAINER } from './container';
import datePickerModule, { DATE_PICKER } from './datePicker';
import dropdownModule, { DROPDOWN } from './dropdown';
import dropdownItemModule, { DROPDOWN_ITEM } from './dropdown/children/dropdownItem';
import flexModule, { FLEX } from './flex';
import formModule, { FORM } from './form';
import gridModule, { GRID } from './grid';
import inputModule, { INPUT } from './input';
import pageHeaderModule, { PAGEHEADER } from './pageHeader';
import radioModule, { RADIO } from './radio';
import sectionModule, { SECTION } from './section';
import selectModule, { SELECT } from './select';
import sliderModule, { SLIDER } from './slider';
import stackModule, { STACK } from './stack';
import switchModule, { SWITCH } from './switch';
import tableModule, { TABLE } from './table';
import tableBadgeModule, { TABLE_TEXT_CELL } from './table/children/tableTextCell';
import tableColumnsModule, { TABLE_COLUMNS } from './table/children/tableColumns';
import tableExpanderCellModule, { TABLE_EXPANDER_CELL } from './table/children/tableExpanderCell';
import tableAmountCellModule, { TABLE_AMOUNT_CELL } from './table/children/tableAmountCell';
import tableFiltersModule, { TABLE_FILTERS } from './table/children/tableFilters';
import tabsModule, { TABS } from './tabs';
import textareaModule, { TEXTAREA } from './textarea';

export function registerAllComponents() {
  register(ASPECT, aspectModule.register);
  register(BUTTON, buttonModule.register);
  register(CARD, cardModule.register);
  register(CAROUSEL, carouselModule.register);
  register(CHART, chartModule.register);
  register(CHECKBOX, checkboxModule.register);
  register(COLUMN, columnModule.register);
  register(COLUMNS, columnsModule.register);
  register(CONTAINER, containerModule.register);
  register(DATE_PICKER, datePickerModule.register);
  register(DROPDOWN, dropdownModule.register);
  register(DROPDOWN_ITEM, dropdownItemModule.register);
  register(FLEX, flexModule.register);
  register(FORM, formModule.register);
  register(GRID, gridModule.register);
  register(INPUT, inputModule.register);
  register(PAGEHEADER, pageHeaderModule.register);
  register(RADIO, radioModule.register);
  register(SECTION, sectionModule.register);
  register(SELECT, selectModule.register);
  register(SLIDER, sliderModule.register);
  register(STACK, stackModule.register);
  register(SWITCH, switchModule.register);
  register(TABLE, tableModule.register);
  register(TABLE_TEXT_CELL, tableBadgeModule.register);
  register(TABLE_COLUMNS, tableColumnsModule.register);
  register(TABLE_EXPANDER_CELL, tableExpanderCellModule.register);
  register(TABLE_FILTERS, tableFiltersModule.register);
  register(TABLE_AMOUNT_CELL, tableAmountCellModule.register);
  register(TABS, tabsModule.register);
  register(TEXTAREA, textareaModule.register);
}