import { initCodeSnippets, initComponents, newPage } from '../src';
import { Layout, PageConfig } from '../src/interfaces/types';
import { OUTPUT_TEST2 } from '../src/utils/testPath';

export const OUTPUT_DIR = OUTPUT_TEST2;

const dashboardLayout: Layout = {
  id: 'grid_dashboard',
  tag: 'grid_dashboard',
  componentName: 'grid',
  properties: {
    variant: 'cols2',
    className: 'border rounded-lg',
    padding: '4',
  },
  children: [
    {
      id: 'flex_sidebar',
      tag: 'flex_sidebar',
      componentName: 'flex',
      properties: {
        variant: 'col',
        className: 'border-r',
        width: '1/4',
        padding: '4',
      },
      children: [
        {
          id: 'card_profile',
          tag: 'card_profile',
          componentName: 'card',
          properties: {
            variant: 'bordered',
          },
        },
      ],
    },
    {
      id: 'container_main',
      tag: 'container_main',
      componentName: 'container',
      properties: {
        variant: 'default',
      },
      children: [
        {
          id: 'section_content',
          tag: 'section_content',
          componentName: 'section',
          properties: {
            className: 'bg-gray-100 rounded-lg',
            padding: '6',
          },
        },
        {
          id: 'label_field',
          tag: 'label_field',
          componentName: 'label',
          content: 'Name',
        },
        {
          id: 'input_field',
          tag: 'input_field',
          componentName: 'input',
          properties: {
            placeholder: 'Enter the name',
          },
        },
        {
          id: 'checkbox_1',
          tag: 'checkbox_1',
          componentName: 'checkbox',
        },
        {
          id: 'button_submit',
          tag: 'button_submit',
          componentName: 'button',
          content: 'Submit',
          interactions: {
            onClick: {
              formSubmit: {
                targetForm: 'form1',
              },
            },
          },
        },
      ],
    },
  ],
};

const pageConfig: PageConfig = {
  type: 'page',
  pageName: 'contribuintes',
  path: 'contribuintes',
  description: 'Lista de Contribuintes',
  forceDynamic: false,
  id: '5ujobhg2qu',
  types: [
    {
      componentId: 'table_8ikc83',
      name: 'table1',
      path: '',
      fields: [
        {
          componentId: 'tablehiddencell_2dudz0',
          name: 'contribuinteId',
          type: 'string',
          required: false,
          defaultValue: '',
        },
        {
          componentId: 'tabletextcell_0v0d2r',
          name: 'numero',
          type: 'string',
          required: false,
          defaultValue: '',
        },
        {
          componentId: 'tabletextcell_vkzdkd',
          name: 'nome',
          type: 'string',
          required: false,
          defaultValue: '',
        },
        {
          componentId: 'tablebadgecell_i6pdrk',
          name: 'regimeDesc',
          type: 'string',
          required: false,
          defaultValue: '',
        },
        {
          componentId: 'tablebadgecell_zie5kn',
          name: 'estatutoJuridicoDesc',
          type: 'string',
          required: false,
          defaultValue: '',
        },
        {
          componentId: 'tabletextcell_b1o1nl',
          name: 'dataEntrada',
          type: 'string',
          required: false,
          defaultValue: '',
        },
        {
          componentId: 'tablebadgecell_0pqc9l',
          name: 'estado',
          type: 'string',
          required: false,
          defaultValue: '',
        },
      ],
    },
  ],
  states: [
    {
      id: 'state_tlz9Y',
      name: 'showFilter',
      type: 'boolean',
      defaultValue: 'false',
      imports: [],
    },
    {
      id: 'state_lDU4Xi',
      name: 'searchValue',
      type: 'string',
      imports: [],
      defaultValue: ' ',
    },
    {
      id: 'state_JvdgxA',
      name: 'openModalCessar',
      type: 'boolean',
      defaultValue: 'false',
      imports: [],
    },
    {
      id: 'state_UdScTo',
      name: 'openPdfPreview',
      type: 'boolean',
      defaultValue: 'false',
      imports: [],
    },
    {
      id: 'state_Ey8TkA',
      name: 'certificadoUrl',
      type: 'string',
      defaultValue: '',
      imports: [],
    },
    {
      id: 'state_ZpvWYR',
      name: 'currentContribuinte',
      type: 'any',
      defaultValue: '',
      imports: [],
    },
    {
      id: 'state_4bbSyL',
      name: 'openModalSuspender',
      type: 'boolean',
      defaultValue: 'false',
      imports: [],
    },
    {
      id: 'state_JkJS12',
      name: 'openModalReativar',
      type: 'boolean',
      defaultValue: 'false',
      imports: [],
    },
  ],
  functions: [
    {
      id: 'fnc_yxSXs',
      name: 'handleDeclaracao',
      code: "const data: any = await emitirDeclaracao(row.contribuinteId);\n//setOpenPdfPreview(!openPdfPreview);\nconsole.log(data)\nif (data && data?.url) \n  window.open(`https://${data.url}`, '_blank', 'noopener,noreferrer');\n\n//setCertificadoUrl(data?.url);\n",
      returnValue: { type: 'void', isNullable: true, isList: false },
      imports: [
        {
          namespace: "import {emitirDeclaracao} from '@/app/(myapp)/hooks/use-contribuinte'",
          id: '5sl1u4o03u',
        },
      ],
      arguments: [
        {
          id: '1',
          name: 'row',
          type: 'any',
          isList: false,
          isOptional: false,
          isInterface: false,
          isFunction: false,
          isState: false,
        },
      ],
      isAsync: true,
    },
    {
      id: 'fnc_m03dV',
      name: 'clearFilters',
      code: 'setSearchValue("")\nsetSelectestatutoJuridicoFtlValue("")\nsetSelectregimeFltValue("")\nsetSelectestadoContruibuinteValue("")\nsetDateRangedatePickerRange1Value(undefined)',
      returnValue: { type: 'void', isNullable: true, isList: false },
      imports: [],
      isAsync: false,
      arguments: [],
    },
  ],
  components: {
    id: 'page_etie93',
    componentName: 'page',
    label: 'page',
    properties: { variant: 'default', commonProperties: { generateReference: false } },
    children: [
      {
        id: 'section_6sx8k0',
        componentName: 'section',
        label: 'section',
        properties: { spaceX: '3', spaceY: '6', commonProperties: {} },
        children: [
          {
            id: 'pageheader_okzejp',
            tag: 'pageHeader1',
            componentName: 'pageHeader',
            label: 'Page Header',
            type: 'group',
            children: [
              {
                id: 'button_32zgrt',
                tag: 'button1',
                componentName: 'button',
                label: 'Button',
                type: 'group',
                children: [],
                interactions: {
                  onClick: {
                    type: 'navigate',
                    function: {
                      fnCustomSet: '() => {}',
                      type: 'function',
                      fnCustomCode: { imports: [] },
                    },
                    action: { actionCustomSet: '() => {}' },
                    navigate: { path: 'contribuintes/novo', name: 'goTonovoContribuinte' },
                  },
                },
                allowTypes: false,
                data: {},
                properties: {
                  content: 'Novo',
                  variant: 'secondary',
                  size: 'default',
                  iconProperties: { showIcon: true, iconName: 'Plus' },
                  commonProperties: { generateReference: false },
                },
                childProperties: {},
                style: {},
              },
            ],
            interactions: {},
            allowTypes: false,
            data: {},
            properties: {
              title: 'Contribuintes',
              description: 'Gerencie os contribuintes do sistema de segurança social',
              variant: 'h3',
              iconProperties: { iconBackButton: 'Search' },
              commonProperties: { generateReference: false },
            },
            childProperties: {},
          },
          {
            id: 'grid_mx6nlw',
            tag: 'grid1',
            componentName: 'grid',
            label: 'Grid',
            type: 'group',
            children: [
              {
                id: 'statscard_bz7hnj',
                tag: 'totalGeral',
                componentName: 'statsCard',
                label: 'Stats Card',
                type: 'group',
                children: [],
                interactions: {
                  onClick: {
                    type: 'function',
                    function: { fnCustomSet: '() => {}', type: 'function' },
                    action: { actionCustomSet: '() => {}' },
                  },
                },
                allowTypes: false,
                data: {
                  value: {
                    state: {
                      id: '',
                      type: 'string | number',
                      name: 'statstatsCard2Value',
                      defaultValue: '0',
                      imports: [],
                      generate: true,
                    },
                    value: { id: '', code: '' },
                  },
                },
                properties: {
                  cardBorderPosition: 'top',
                  cardBorder: 'rounded-md',
                  cardVariant: 'info',
                  iconBackground: 'rounded',
                  title: 'Total Geral',
                  titleSize: 'sm',
                  valueSize: 'sm',
                  iconProperties: {
                    showIcon: true,
                    iconName: 'Building',
                    iconSize: 'md',
                    iconVariant: 'info',
                    iconPlacement: 'end',
                  },
                  itemPlacement: 'start',
                  commonProperties: { generateReference: false },
                  showIconBackground: true,
                },
                childProperties: {},
              },
              {
                id: 'statscard_9o59o8',
                tag: 'statsCard1',
                componentName: 'statsCard',
                label: 'Stats Card',
                type: 'group',
                children: [],
                interactions: {
                  onClick: {
                    type: 'function',
                    function: { fnCustomSet: '() => {}', type: 'function' },
                    action: { actionCustomSet: '() => {}' },
                  },
                },
                allowTypes: false,
                data: {
                  value: {
                    state: {
                      id: '',
                      type: 'string | number',
                      name: 'statstatsCard1Value',
                      defaultValue: '0',
                      imports: [],
                      generate: true,
                    },
                    value: { id: '', code: '' },
                  },
                },
                properties: {
                  cardBorderPosition: 'top',
                  cardBorder: 'rounded-md',
                  cardVariant: 'success',
                  iconBackground: 'rounded',
                  title: 'Total Ativos',
                  titleSize: 'sm',
                  valueSize: 'lg',
                  iconProperties: {
                    showIcon: true,
                    iconName: 'CircleCheckBig',
                    iconSize: 'md',
                    iconVariant: 'success',
                    iconPlacement: 'end',
                  },
                  itemPlacement: 'start',
                  commonProperties: { generateReference: false },
                  showIconBackground: true,
                  showIconBorder: true,
                },
                childProperties: {},
              },
              {
                id: 'statscard_9fseux',
                tag: 'statsCard3',
                componentName: 'statsCard',
                label: 'Stats Card',
                type: 'group',
                children: [],
                interactions: {
                  onClick: {
                    type: 'function',
                    function: { fnCustomSet: '() => {}', type: 'function' },
                    action: { actionCustomSet: '() => {}' },
                  },
                },
                allowTypes: false,
                data: {
                  value: {
                    state: {
                      id: '',
                      type: 'string | number',
                      name: 'statstatsCard3Value',
                      defaultValue: '0',
                      imports: [],
                      generate: true,
                    },
                    value: { id: '', code: '' },
                  },
                },
                properties: {
                  cardBorderPosition: 'top',
                  cardBorder: 'rounded-md',
                  cardVariant: 'indigo',
                  iconBackground: 'rounded',
                  title: 'Total Regime Geral',
                  titleSize: 'sm',
                  valueSize: 'sm',
                  iconProperties: {
                    showIcon: true,
                    iconName: 'Briefcase',
                    iconSize: 'md',
                    iconVariant: 'warning',
                    iconPlacement: 'end',
                  },
                  itemPlacement: 'start',
                  commonProperties: { generateReference: false },
                  showIconBackground: true,
                },
                childProperties: {},
              },
              {
                id: 'statscard_1cxoyd',
                tag: 'statsCard4',
                componentName: 'statsCard',
                label: 'Stats Card',
                type: 'group',
                children: [],
                interactions: {
                  onClick: {
                    type: 'function',
                    function: { fnCustomSet: '() => {}', type: 'function' },
                    action: { actionCustomSet: '() => {}' },
                  },
                },
                allowTypes: false,
                data: {
                  value: {
                    state: {
                      id: '',
                      type: 'string | number',
                      name: 'statstatsCard4Value',
                      defaultValue: '0',
                      imports: [],
                      generate: true,
                    },
                    value: { id: '', code: '' },
                  },
                },
                properties: {
                  cardBorderPosition: 'top',
                  cardBorder: 'rounded-md',
                  cardVariant: 'warning',
                  iconBackground: 'rounded',
                  title: 'Total Conta Própria',
                  titleSize: 'sm',
                  valueSize: 'sm',
                  iconProperties: {
                    showIcon: true,
                    iconName: 'UsersRound',
                    iconSize: 'md',
                    iconVariant: 'indigo',
                    iconPlacement: 'end',
                  },
                  itemPlacement: 'start',
                  commonProperties: { generateReference: false },
                  showIconBackground: true,
                },
                childProperties: {},
              },
            ],
            interactions: {},
            allowTypes: false,
            data: {},
            properties: {
              gap: 4,
              variant: { default: 'cols1', md: 'cols2', lg: 'cols4', xs: '', xl: '' },
              commonProperties: { generateReference: false },
            },
            childProperties: { className: 'col-span-1' },
          },
          {
            id: 'container_us5b4f',
            tag: 'container4',
            componentName: 'container',
            label: 'Container',
            type: 'group',
            children: [
              {
                id: 'container_cua2ew',
                tag: 'container1',
                componentName: 'container',
                label: 'Container',
                type: 'group',
                children: [
                  {
                    id: 'container_rb9e8l',
                    tag: 'container2',
                    componentName: 'container',
                    label: 'Container',
                    type: 'group',
                    children: [
                      {
                        id: 'container_f7tvd0',
                        tag: 'container3',
                        componentName: 'container',
                        label: 'Container',
                        type: 'group',
                        children: [
                          {
                            id: 'inputsearch_m9mipl',
                            tag: 'inputSearch2',
                            componentName: 'inputSearch',
                            label: 'Input Search',
                            type: 'group',
                            children: [],
                            interactions: {
                              setValueChange: {
                                type: 'function',
                                function: {
                                  fnCustomSet: '',
                                  type: 'function',
                                  fnCustomCode: { imports: [] },
                                },
                                action: { actionCustomSet: "(value) => ''" },
                              },
                              onSearch: {
                                type: 'function',
                                function: {
                                  fnCustomCode: { imports: [] },
                                  fnCustomSet: '(value) => setSearchValue(value )\n',
                                },
                              },
                            },
                            allowTypes: false,
                            data: {
                              value: {
                                state: {
                                  id: '',
                                  name: 'searchValue',
                                  type: '',
                                  imports: [],
                                  generate: false,
                                },
                              },
                            },
                            properties: {
                              label: '',
                              iconProperties: {
                                showStartIcon: true,
                                startIcon: 'Search',
                                submitIcon: 'ArrowRight',
                              },
                              required: false,
                              dataProperties: { isVirtual: false, isType: true },
                              commonProperties: { generateReference: false },
                              placeholder: 'Pesquisar contribuintes por nome ou número...',
                              showSubmitButton: true,
                              submitButtonLabel: 'Pesquisar',
                              className: 'py-1',
                            },
                            childProperties: {},
                          },
                        ],
                        interactions: {},
                        allowTypes: false,
                        data: {},
                        properties: { className: 'flex-1 min-w-[240px]', commonProperties: {} },
                        childProperties: {},
                      },
                      {
                        id: 'flex_kujoxb',
                        tag: 'flex1',
                        componentName: 'flex',
                        label: 'Flex',
                        type: 'group',
                        children: [
                          {
                            id: 'button_3jl0xm',
                            tag: 'button3',
                            componentName: 'button',
                            label: 'Button',
                            type: 'group',
                            children: [],
                            interactions: {
                              onClick: {
                                type: 'function',
                                function: {
                                  fnCustomSet: '() => {setShowFilter(!showFilter)\n}',
                                  fnCustomCode: { imports: [] },
                                  type: 'function',
                                },
                                action: {},
                              },
                            },
                            allowTypes: false,
                            data: {},
                            properties: {
                              content: 'Filtros',
                              variant: 'outline',
                              size: 'default',
                              iconProperties: { showIcon: true, iconName: 'SlidersHorizontal' },
                              commonProperties: { generateReference: false },
                            },
                            childProperties: {},
                          },
                          {
                            id: 'button_u6qhn5',
                            tag: 'button2',
                            componentName: 'button',
                            label: 'Button',
                            type: 'group',
                            children: [],
                            interactions: {
                              onClick: {
                                type: 'function',
                                function: {
                                  fnName: 'clearFilters',
                                  fnCustomSet: '() => {}',
                                  fnCustomCode: { imports: [] },
                                  type: 'function',
                                },
                                action: {},
                              },
                            },
                            allowTypes: false,
                            data: {},
                            properties: {
                              content: 'Button',
                              variant: 'outline',
                              size: 'icon',
                              iconProperties: { showIcon: true, iconName: 'RefreshCcw' },
                              commonProperties: { generateReference: false },
                            },
                            childProperties: {},
                          },
                        ],
                        interactions: {},
                        allowTypes: false,
                        data: {},
                        properties: { commonProperties: {} },
                        childProperties: {},
                        style: {
                          layout: {
                            type: 'flex',
                            flex: {
                              direction: 'row',
                              wrap: 'wrap',
                              alignItems: 'stretch',
                              justifyContent: 'flex-end',
                              gap: '2',
                            },
                            grid: {
                              templateColumns: '1',
                              templateRows: '1',
                              gap: '2',
                              justifyItems: 'start',
                              alignItems: 'start',
                              direction: 'row',
                              dense: false,
                            },
                            block: {},
                          },
                        },
                      },
                    ],
                    interactions: {},
                    allowTypes: false,
                    data: {},
                    properties: { commonProperties: {}, className: '' },
                    childProperties: {},
                    style: {
                      layout: {
                        type: 'flex',
                        flex: {
                          direction: 'row',
                          wrap: 'wrap',
                          alignItems: 'center',
                          justifyContent: 'space-between',
                          gap: '2',
                        },
                        grid: {
                          templateColumns: '1',
                          templateRows: '1',
                          gap: '2',
                          justifyItems: 'start',
                          alignItems: 'start',
                          direction: 'row',
                          dense: false,
                        },
                        block: {},
                      },
                    },
                  },
                  {
                    id: 'separator_ivc9k0',
                    tag: 'separator1',
                    componentName: 'separator',
                    label: 'Separator',
                    type: 'group',
                    children: [],
                    interactions: {},
                    allowTypes: false,
                    data: {},
                    properties: {
                      orientation: 'horizontal',
                      className: 'my-3',
                      commonProperties: {},
                    },
                    childProperties: {},
                    rules: [{ type: 'visibility', condition: 'showFilter' }],
                  },
                  {
                    id: 'grid_l18109',
                    tag: 'grid2',
                    componentName: 'grid',
                    label: 'Grid',
                    type: 'group',
                    children: [
                      {
                        id: 'combobox_ihrmw0',
                        tag: 'estatutoJuridicoFtl',
                        componentName: 'combobox',
                        label: 'Combobox',
                        type: 'group',
                        children: [],
                        interactions: {
                          onChange: {
                            type: 'function',
                            function: {
                              fnCustomSet:
                                '(value) => { setSelectestatutoJuridicoFtlValue(value as string) }',
                              type: 'function',
                              fnCustomCode: { imports: [] },
                            },
                            action: {},
                          },
                        },
                        allowTypes: false,
                        data: {
                          value: {
                            state: {
                              id: '',
                              type: 'string',
                              name: 'select{{id}}Value',
                              defaultValue: '{{value}}',
                              imports: [],
                              generate: true,
                            },
                            value: { id: '', code: '' },
                          },
                          options: {
                            state: {
                              id: '',
                              type: 'IGRPOptionsProps[]',
                              name: 'select{{id}}Options',
                              defaultValue: '[]',
                              imports: [],
                              generate: true,
                            },
                            value: { id: '', code: '' },
                          },
                        },
                        properties: {
                          label: 'Estatuto Jurídico',
                          variant: 'single',
                          placeholder: 'Select an option...',
                          selectLabel: 'No option found',
                          showSearch: true,
                          iconProperties: { showIcon: false, iconName: 'CornerDownRight' },
                          dataProperties: { isVirtual: false, isType: true },
                          commonProperties: { generateReference: false },
                          gridSize: 'full',
                          options: [],
                        },
                        childProperties: {},
                      },
                      {
                        id: 'combobox_p5uzc8',
                        tag: 'regimeFlt',
                        componentName: 'combobox',
                        label: 'Combobox',
                        type: 'group',
                        children: [],
                        interactions: {
                          onChange: {
                            type: 'function',
                            function: {
                              fnCustomSet:
                                '(value) => { setSelectregimeFltValue(value as string) }\n',
                              type: 'function',
                              fnCustomCode: { imports: [] },
                            },
                            action: {},
                          },
                        },
                        allowTypes: false,
                        data: {
                          value: {
                            state: {
                              id: '',
                              type: 'string',
                              name: 'select{{id}}Value',
                              defaultValue: '{{value}}',
                              imports: [],
                              generate: true,
                            },
                            value: { id: '', code: '' },
                          },
                          options: {
                            state: {
                              id: '',
                              type: 'IGRPOptionsProps[]',
                              name: 'select{{id}}Options',
                              defaultValue: '[]',
                              imports: [],
                              generate: true,
                            },
                            value: { id: '', code: '' },
                          },
                        },
                        properties: {
                          label: 'Regime',
                          variant: 'single',
                          placeholder: 'Select an option...',
                          selectLabel: 'No option found',
                          showSearch: true,
                          iconProperties: { showIcon: false, iconName: 'CornerDownRight' },
                          dataProperties: { isVirtual: false, isType: true },
                          commonProperties: { generateReference: false },
                          gridSize: 'full',
                          options: [],
                        },
                        childProperties: {},
                      },
                      {
                        id: 'combobox_5nu8z6',
                        tag: 'estadoContruibuinte',
                        componentName: 'combobox',
                        label: 'Combobox',
                        type: 'group',
                        children: [],
                        interactions: {
                          onChange: {
                            type: 'function',
                            function: {
                              fnCustomSet:
                                '(value) => { setSelectestadoContruibuinteValue(value as string) }',
                              type: 'function',
                              fnCustomCode: { imports: [] },
                            },
                            action: {},
                          },
                        },
                        allowTypes: false,
                        data: {
                          value: {
                            state: {
                              id: '',
                              type: 'string',
                              name: 'select{{id}}Value',
                              defaultValue: '{{value}}',
                              imports: [],
                              generate: true,
                            },
                          },
                          options: {
                            state: {
                              id: '',
                              type: 'IGRPOptionsProps[]',
                              name: 'select{{id}}Options',
                              defaultValue: '[]',
                              imports: [],
                              generate: true,
                            },
                          },
                        },
                        properties: {
                          label: 'Estado do contruibuinte',
                          variant: 'single',
                          placeholder: 'Select an option...',
                          selectLabel: 'No option found',
                          showSearch: true,
                          iconProperties: { showIcon: false, iconName: 'CornerDownRight' },
                          dataProperties: { isVirtual: false, isType: true },
                          commonProperties: { generateReference: false },
                          gridSize: 'full',
                          options: [],
                        },
                        childProperties: {},
                      },
                      {
                        id: 'datepickerrange_w99onj',
                        tag: 'datePickerRange1',
                        componentName: 'datePickerRange',
                        label: 'Date Range',
                        type: 'group',
                        children: [],
                        interactions: {
                          onDateChange: {
                            type: 'function',
                            function: { type: 'function' },
                            action: {},
                          },
                        },
                        allowTypes: false,
                        data: {
                          date: {
                            state: {
                              id: '',
                              type: 'DateRange | undefined',
                              name: 'dateRangedatePickerRange1Value',
                              defaultValue: '{ from: undefined, to: undefined }',
                              imports: [],
                              generate: true,
                            },
                            value: { id: '', code: '' },
                          },
                        },
                        properties: {
                          placeholder: 'Enter the date',
                          dateFormat: 'dd/MM/yyyy',
                          gridSize: 'full',
                          commonProperties: { generateReference: false },
                          label: 'Periodo de Inscriçāo',
                        },
                        childProperties: {},
                      },
                    ],
                    interactions: {},
                    allowTypes: false,
                    data: {},
                    properties: {
                      gap: 4,
                      variant: { default: 'cols1', md: 'cols2', lg: 'cols4' },
                      commonProperties: { generateReference: false },
                    },
                    childProperties: { className: 'col-span-1 ' },
                    style: {},
                    rules: [{ type: 'visibility', condition: 'showFilter' }],
                  },
                  {
                    id: 'flex_gzk6wy',
                    tag: 'flex2',
                    componentName: 'flex',
                    label: 'Flex',
                    type: 'group',
                    children: [
                      {
                        id: 'button_2c64es',
                        tag: 'button5',
                        componentName: 'button',
                        label: 'Button',
                        type: 'group',
                        children: [],
                        interactions: {
                          onClick: {
                            type: 'function',
                            function: {
                              fnCustomSet: '() => {}',
                              type: 'function',
                              fnCustomCode: { imports: [] },
                              fnName: 'clearFilters',
                            },
                            action: { actionCustomSet: '() => {}' },
                          },
                        },
                        allowTypes: false,
                        data: {},
                        properties: {
                          content: 'Limpar Filtros',
                          variant: 'outline',
                          size: 'default',
                          iconProperties: { showIcon: true, iconName: 'X' },
                          commonProperties: { generateReference: false },
                          disabled: false,
                        },
                        childProperties: {},
                      },
                    ],
                    interactions: {},
                    allowTypes: false,
                    data: {},
                    properties: { commonProperties: {}, className: '' },
                    childProperties: {},
                    style: {
                      layout: {
                        type: 'flex',
                        flex: {
                          direction: 'row',
                          wrap: 'wrap',
                          alignItems: 'stretch',
                          justifyContent: 'flex-end',
                          gap: '2',
                        },
                        grid: {
                          templateColumns: '1',
                          templateRows: '1',
                          gap: '2',
                          justifyItems: 'start',
                          alignItems: 'start',
                          direction: 'row',
                          dense: false,
                        },
                        block: {},
                      },
                    },
                    rules: [{ type: 'visibility', condition: 'showFilter' }],
                  },
                ],
                interactions: {},
                allowTypes: false,
                data: {},
                properties: { className: 'px-4 pt-2 space-y-3', commonProperties: {} },
                childProperties: {},
              },
              {
                id: 'table_8ikc83',
                tag: 'table1',
                componentName: 'table',
                label: 'Table',
                type: 'group',
                children: [
                  {
                    id: 'tablecolumns_bk6z31',
                    tag: 'tableColumns1',
                    componentName: 'tableColumns',
                    label: 'Table Column',
                    children: [
                      {
                        id: 'tablehiddencell_2dudz0',
                        tag: 'contribuinteId',
                        componentName: 'tableHiddenCell',
                        label: 'Hidden Column',
                        type: '',
                        children: [],
                        interactions: {},
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerTitle: 'contribuinteId',
                          value: '',
                          dataProperties: { isVirtual: false, isType: true },
                          commonProperties: {},
                        },
                        childProperties: {},
                      },
                      {
                        id: 'tabletextcell_0v0d2r',
                        tag: 'numero',
                        componentName: 'tableTextCell',
                        label: 'Text Column',
                        type: '',
                        children: [],
                        interactions: {},
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerTitle: 'Número',
                          dataProperties: { isVirtual: false, isType: true },
                          variant: 'default',
                          commonProperties: { generateReference: false },
                          headerType: 'sortToggle',
                        },
                        childProperties: {},
                      },
                      {
                        id: 'tabletextcell_vkzdkd',
                        tag: 'nome',
                        componentName: 'tableTextCell',
                        label: 'Text Column',
                        type: '',
                        children: [],
                        interactions: {},
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerType: 'sortToggle',
                          headerTitle: 'Nome',
                          dataProperties: { isVirtual: false, isType: true },
                          variant: 'default',
                          commonProperties: {},
                        },
                        childProperties: {},
                      },
                      {
                        id: 'tablebadgecell_i6pdrk',
                        tag: 'regimeDesc',
                        componentName: 'tableBadgeCell',
                        label: 'Badge Column',
                        type: '',
                        children: [],
                        interactions: {
                          customize: {
                            type: 'function',
                            function: { type: 'function' },
                            action: {},
                          },
                        },
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerTitle: 'Regime',
                          dataProperties: { isVirtual: false, isType: true },
                          iconProperties: {
                            showIcon: false,
                            iconName: 'Info',
                            iconPlacement: 'start',
                          },
                          variant: 'soft',
                          commonProperties: { generateReference: false },
                          headerType: 'sortToggle',
                        },
                        childProperties: {},
                      },
                      {
                        id: 'tablebadgecell_zie5kn',
                        tag: 'estatutoJuridicoDesc',
                        componentName: 'tableBadgeCell',
                        label: 'Badge Column',
                        type: '',
                        children: [],
                        interactions: {
                          customize: {
                            type: 'function',
                            function: { type: 'function' },
                            action: {},
                          },
                        },
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerTitle: 'Estatuto Jurídico',
                          dataProperties: { isVirtual: false, isType: true },
                          iconProperties: {
                            showIcon: false,
                            iconName: 'Info',
                            iconPlacement: 'start',
                          },
                          variant: 'soft',
                          commonProperties: {},
                        },
                        childProperties: {},
                      },
                      {
                        id: 'tabletextcell_b1o1nl',
                        tag: 'dataEntrada',
                        componentName: 'tableTextCell',
                        label: 'Text Column',
                        type: '',
                        children: [],
                        interactions: {},
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerTitle: 'Data de Registo',
                          dataProperties: { isVirtual: false, isType: true },
                          variant: 'default',
                          commonProperties: {},
                        },
                        childProperties: {},
                      },
                      {
                        id: 'tablebadgecell_0pqc9l',
                        tag: 'estado',
                        componentName: 'tableBadgeCell',
                        label: 'Badge Column',
                        type: '',
                        children: [],
                        interactions: {
                          customize: {
                            type: 'function',
                            function: {
                              type: 'function',
                              fnCustomCode: {
                                imports: [
                                  {
                                    namespace:
                                      "import {getStatusColor} from '@/app/(myapp)/functions/global'",
                                    id: 'p32e9k7w3r',
                                  },
                                ],
                              },
                              fnName: 'getStatusColor',
                            },
                            action: {},
                          },
                        },
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerTitle: 'Estado',
                          dataProperties: { isVirtual: false, isType: true },
                          iconProperties: {
                            showIcon: false,
                            iconName: 'Info',
                            iconPlacement: 'start',
                          },
                          variant: 'soft',
                          commonProperties: { generateReference: false },
                        },
                        childProperties: {},
                      },
                      {
                        id: 'tableactionlistcell_rz79fw',
                        tag: 'tableActionListCell1',
                        componentName: 'tableActionListCell',
                        label: 'Actions Column',
                        type: '',
                        children: [
                          {
                            id: 'tablelinkaction_f0a3j2',
                            tag: 'tableLinkAction1',
                            componentName: 'tableLinkAction',
                            label: 'Link Action',
                            type: '',
                            children: [],
                            interactions: {},
                            allowTypes: false,
                            data: {},
                            properties: {
                              labelTrigger: 'Visualizar',
                              iconProperties: { iconName: 'Eye' },
                              variant: 'ghost',
                              type: 'link',
                              href: 'contribuintes/[uuid]',
                              commonProperties: { generateReference: false },
                              segments: [
                                { name: '[uuid]', tag: 'contribuinteId', context: 'column' },
                              ],
                              params: [],
                            },
                            childProperties: {},
                          },
                          {
                            id: 'tablelinkaction_lv8blu',
                            tag: 'tableLinkAction2',
                            componentName: 'tableLinkAction',
                            label: 'Link Action',
                            type: '',
                            children: [],
                            interactions: {},
                            allowTypes: false,
                            data: {},
                            properties: {
                              labelTrigger: 'Editar',
                              iconProperties: { iconName: 'SquarePen' },
                              variant: 'ghost',
                              href: 'contribuintes/[uuid]/edit',
                              commonProperties: { generateReference: false },
                              segments: [
                                { name: '[uuid]', tag: 'contribuinteId', context: 'column' },
                              ],
                              params: [],
                            },
                            childProperties: {},
                            rules: [{ type: 'visibility', condition: "rowData.estado === 'A'" }],
                          },
                          {
                            id: 'tabledropdownmenucell_1t20lu',
                            tag: 'tableDropdownMenuCell1',
                            componentName: 'tableDropdownMenuCell',
                            label: 'Dropdown Column',
                            type: '',
                            children: [
                              {
                                id: 'tablecustomdropdownitem_eo1dyf',
                                tag: 'tableCustomDropdownItem2',
                                componentName: 'tableCustomDropdownItem',
                                label: 'Custom Item',
                                type: '',
                                children: [],
                                interactions: {
                                  action: {
                                    type: 'function',
                                    function: {
                                      fnCustomCode: { imports: [] },
                                      fnCustomSet:
                                        '()=> { setCurrentContribuinte(rowData);\nsetOpenModalSuspender(!openModalSuspender)}\n',
                                    },
                                  },
                                },
                                allowTypes: false,
                                data: {},
                                properties: {
                                  labelTrigger: 'Suspender',
                                  showIcon: true,
                                  iconProperties: { iconName: 'CircleAlert' },
                                  commonProperties: { generateReference: false },
                                },
                                childProperties: {},
                              },
                              {
                                id: 'tablecustomdropdownitem_6qq5ee',
                                tag: 'tableCustomDropdownItem1',
                                componentName: 'tableCustomDropdownItem',
                                label: 'Custom Item',
                                type: '',
                                children: [],
                                interactions: {
                                  action: {
                                    type: 'function',
                                    function: {
                                      fnCustomCode: { imports: [] },
                                      fnCustomSet:
                                        '() => {\n  setCurrentContribuinte(rowData);\n  setOpenModalCessar(!openModalCessar)\n}',
                                    },
                                  },
                                },
                                allowTypes: false,
                                data: {},
                                properties: {
                                  labelTrigger: 'Cessar',
                                  showIcon: true,
                                  iconProperties: { iconName: 'ArchiveX' },
                                  commonProperties: { generateReference: false },
                                },
                                childProperties: {},
                              },
                              {
                                id: 'tablecustomdropdownitem_09hjh0',
                                tag: 'tableCustomDropdownItem3',
                                componentName: 'tableCustomDropdownItem',
                                label: 'Custom Item',
                                type: '',
                                children: [],
                                interactions: {
                                  action: {
                                    type: 'function',
                                    function: {
                                      fnCustomSet:
                                        '() => {setOpenModalReativar(!openModalReativar)\nsetCurrentContribuinte(rowData)\n\n}',
                                      fnCustomCode: { imports: [] },
                                      type: 'function',
                                    },
                                    action: {},
                                  },
                                },
                                allowTypes: false,
                                data: {},
                                properties: {
                                  labelTrigger: 'Reativar',
                                  showIcon: true,
                                  iconProperties: { iconName: 'UserCheck' },
                                  commonProperties: { generateReference: false },
                                },
                                childProperties: {},
                                rules: [
                                  { type: 'visibility', condition: "rowData.status === 'A'" },
                                ],
                              },
                              {
                                id: 'tablelinkdropdownitem_2o8t7u',
                                tag: 'tableLinkDropdownItem1u',
                                componentName: 'tableLinkDropdownItem',
                                label: 'Link Item',
                                type: '',
                                children: [],
                                interactions: {},
                                allowTypes: false,
                                data: {},
                                properties: {
                                  labelTrigger: 'Inscrição de Beneficiário',
                                  showIcon: true,
                                  iconProperties: { iconName: 'LifeBuoy' },
                                  href: 'utentes/novo',
                                  commonProperties: { generateReference: false },
                                  params: [
                                    {
                                      name: 'contribuinteId',
                                      tag: 'contribuinteId',
                                      context: 'column',
                                    },
                                  ],
                                },
                                childProperties: {},
                              },
                              {
                                id: 'tablelinkdropdownitem_bxoeeo',
                                tag: 'tableLinkDropdownItem3',
                                componentName: 'tableLinkDropdownItem',
                                label: 'Link Item',
                                type: '',
                                children: [],
                                interactions: {},
                                allowTypes: false,
                                data: {},
                                properties: {
                                  labelTrigger: 'Ver Beneficiarios',
                                  showIcon: true,
                                  iconProperties: { iconName: 'UsersRound' },
                                  href: 'utentes',
                                  commonProperties: { generateReference: false },
                                  params: [
                                    {
                                      name: 'contribuinteId',
                                      tag: 'contribuinteId',
                                      context: 'column',
                                    },
                                  ],
                                },
                                childProperties: {},
                              },
                              {
                                id: 'tablealertdropdownitem_jdblz5',
                                tag: 'tableAlertDropdownItem19',
                                componentName: 'tableAlertDropdownItem',
                                label: 'Alert Item',
                                type: '',
                                children: [],
                                interactions: {
                                  onClickConfirm: {
                                    type: 'function',
                                    function: {
                                      fnCustomSet: '() => {handleDeclaracao(rowData)}',
                                      type: 'function',
                                      fnCustomCode: { imports: [] },
                                    },
                                    action: {},
                                  },
                                },
                                allowTypes: false,
                                data: {},
                                properties: {
                                  showIcon: true,
                                  iconProperties: { iconName: 'FileText' },
                                  modalTitle: 'Emitir Declaração',
                                  content: 'Deseja efectuar essa operaçāo?',
                                  showCancel: true,
                                  labelCancel: 'Cancel',
                                  variantCancel: 'outline',
                                  showConfirm: true,
                                  labelConfirm: 'Confirm',
                                  variantConfirm: 'default',
                                  commonProperties: { generateReference: false },
                                  labelTrigger: 'Declaração',
                                },
                                childProperties: {},
                              },
                            ],
                            interactions: {},
                            allowTypes: false,
                            data: {},
                            properties: {
                              labelTrigger: 'Dropdown Actions',
                              iconProperties: { iconName: 'ArrowRight' },
                              variant: 'default',
                              commonProperties: { generateReference: false },
                            },
                            childProperties: {},
                          },
                        ],
                        interactions: {},
                        allowTypes: false,
                        data: {},
                        properties: {
                          headerTitle: '',
                          type: 'inline',
                          commonProperties: { generateReference: false },
                          className: 'text-center',
                        },
                        childProperties: {},
                      },
                    ],
                    interactions: {},
                    allowTypes: false,
                    data: {},
                    properties: { commonProperties: {} },
                    childProperties: {},
                  },
                  {
                    id: 'tablefilters_pi9a7r',
                    tag: 'tableFilters1',
                    componentName: 'tableFilters',
                    label: 'Table Filter',
                    children: [],
                    interactions: {},
                    allowTypes: false,
                    data: {},
                    properties: { commonProperties: {} },
                  },
                ],
                interactions: {},
                allowTypes: true,
                data: {
                  data: {
                    state: {
                      id: '',
                      type: 'Table1[]',
                      name: 'contentTabletable1',
                      defaultValue: '[]',
                      imports: [],
                      generate: true,
                    },
                    value: { id: '', code: '' },
                  },
                },
                properties: {
                  commonProperties: { generateReference: false },
                  showFilter: true,
                  showPagination: true,
                  tableClassName: 'rounded-none',
                  paginationClassName: 'px-3 pb-3',
                },
                dataType: 'table1',
                childProperties: {},
              },
            ],
            interactions: {},
            allowTypes: false,
            data: {},
            properties: { className: 'border rounded-sm', commonProperties: {} },
            childProperties: {},
          },
        ],
        tag: 'section2',
        data: {},
        interactions: {},
        childProperties: {},
      },
      {
        id: 'section_dlmiao',
        componentName: 'section',
        label: 'section',
        properties: {},
        children: [
          {
            id: 'pdfpreviewmodal_nevrx7',
            tag: 'PdfPreviewModal1',
            componentName: 'PdfPreviewModal',
            label: 'Pdf Preview Modal',
            type: 'group',
            children: [],
            interactions: {
              setIsOpen: {
                type: 'function',
                function: {
                  fnCustomCode: { imports: [] },
                  fnCustomSet: '()=>setOpenPdfPreview(!openPdfPreview)\n',
                },
              },
            },
            allowTypes: false,
            data: {
              isOpen: {
                state: {
                  id: '',
                  name: 'openPdfPreview',
                  type: '',
                  imports: [],
                  generate: false,
                },
              },
              pdfurl: {
                state: { id: '', name: 'certificadoUrl', type: '', imports: [], generate: false },
              },
            },
            properties: { customProperties: {} },
            childProperties: {},
          },
          {
            id: 'reativarcontribuinte_ie2l0u',
            tag: 'ReativarContribuinte1',
            componentName: 'ReativarContribuinte',
            label: 'Reativar Contribuinte',
            type: 'group',
            children: [],
            interactions: {
              setOpen: {
                type: 'function',
                function: {
                  fnCustomCode: { imports: [] },
                  fnCustomSet: '()=>setOpenModalReativar(!openModalReativar)\n',
                },
              },
            },
            allowTypes: false,
            data: {
              open: {
                state: {
                  id: '',
                  name: 'openModalReativar',
                  type: '',
                  imports: [],
                  generate: false,
                },
              },
              contribuinte: {
                state: {
                  id: '',
                  name: 'currentContribuinte',
                  type: '',
                  imports: [],
                  generate: false,
                },
              },
            },
            properties: { customProperties: {} },
            childProperties: {},
          },
          {
            id: 'cessarcontribuinte_r9bi3y',
            tag: 'Cessarcontribuinte1',
            componentName: 'Cessarcontribuinte',
            label: 'Cessar Contribuinte',
            type: 'group',
            children: [],
            interactions: {
              setOpen: {
                type: 'function',
                function: {
                  fnCustomCode: { imports: [] },
                  fnCustomSet: '()=>setOpenModalCessar(!openModalCessar)\n',
                },
              },
            },
            allowTypes: false,
            data: {
              open: {
                state: {
                  id: '',
                  name: 'openModalCessar',
                  type: '',
                  imports: [],
                  generate: false,
                },
              },
              contribuinte: {
                state: {
                  id: '',
                  name: 'currentContribuinte',
                  type: '',
                  imports: [],
                  generate: false,
                },
              },
            },
            properties: { customProperties: {} },
            childProperties: {},
          },
          {
            id: 'suspendercontribuinte_vst6ab',
            tag: 'SuspenderContribuinte12',
            componentName: 'SuspenderContribuinte',
            label: 'Suspender Contribuinte',
            type: 'group',
            children: [],
            interactions: {
              setOpen: {
                type: 'function',
                function: {
                  fnCustomCode: { imports: [] },
                  fnCustomSet: '()=>setOpenModalSuspender(!openModalSuspender)\n',
                },
              },
            },
            allowTypes: false,
            data: {
              contribuinte: {
                state: {
                  id: '',
                  name: 'currentContribuinte',
                  type: '',
                  imports: [],
                  generate: false,
                },
              },
              open: {
                state: {
                  id: '',
                  name: 'openModalSuspender',
                  type: '',
                  imports: [],
                  generate: false,
                },
              },
            },
            properties: { customProperties: {} },
            childProperties: {},
            customProperties: {},
          },
        ],
        tag: '',
        data: {},
        interactions: {},
      },
    ],
    tag: 'page2',
    data: {},
    interactions: {
      onLoad: {
        type: 'function',
        function: {
          type: 'function',
          fnCustomCode: {
            imports: [
              {
                namespace: "import {useContribuinte} from '@/app/(myapp)/hooks/use-contribuinte'",
                id: 'vl8sc2k2k',
              },
              {
                id: 'import_rk6264',
                namespace:
                  "import { IGRPLoadingSpinner } from '@igrp/igrp-framework-react-design-system';",
              },
              {
                id: 'import_9lDmWt',
                namespace:
                  "import {useContribuinteParameterizations} from '@/app/(myapp)/hooks/use-parameterization'",
              },
            ],
            fnCode:
              'const { data, stats, isLoading, error } = useContribuinte({\n  search: searchValue,\n  regime: selectregimeFltValue,\n  estatutoJuridico: selectestatutoJuridicoFtlValue,\n  estado: selectestadoContruibuinteValue,\n  data: dateRangedatePickerRange1Value,\n});\n\nconst {\n  estatutoJuridico,\n  regimes,\n  estadosContribuinte,\n  isLoading: isLoadingParams,\n} = useContribuinteParameterizations();\n\nuseEffect(() => {\n  if (isLoadingParams) return;\n  setSelectregimeFltOptions(regimes || []);\n  setSelectestadoContruibuinteOptions(estadosContribuinte || [])\n  setSelectestatutoJuridicoFtlOptions(estatutoJuridico || []);\n}, [isLoadingParams]);\n\nuseEffect(() => {\n  if (isLoading || !data || !data.content) return\n  setContentTabletable1(\n    (data.content || []).map((item: any) => ({\n      ...item,\n    })),\n  );\n  setStatstatsCard1Value(stats?.active || 0);\n  setStatstatsCard2Value(stats?.total || 0);\n  setStatstatsCard3Value(stats?.regimeGeral || 0);\n  setStatstatsCard4Value(stats?.regimeContaPropria || 0);\n\n}, [isLoading, data]);\n\nif (isLoading && !error) {\n    return (\n      <div className="flex items-center gap2 flex-col">\n        <IGRPLoadingSpinner />\n        <span> loading contribuintes...</span>\n      </div>\n    );\n  }',
          },
        },
        action: {},
      },
    },
    childProperties: {},
  },
  imports: [],
};

beforeAll(async () => {
  await initComponents();
  await initCodeSnippets();
});

describe('Page module', () => {
  it('should save the page configuration file', async () => {
    await newPage(pageConfig, OUTPUT_DIR);
  });
});
